### PR TITLE
Update ZIO to 1.0.0-RC21

### PR DESCRIPTION
**Pull request by ghostdogpr**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Weird, the tests pass on my machine 🤔

**Comment by ghostdogpr** [comment]
Any idea what’s going on with the test timeouts? Did zipPar become slower? It only take a few seconds on my machine.

**Comment by adamgfraser** [comment]
Looking into it now. I'm wondering if we are building chunks internally in a way that is not efficient with the new balanced concatenation, like in that benchmark we were talking about.

**Comment by adamgfraser** [comment]
Hmmm, I am not sure what is going on at this point. I thought it was an issue with efficiency of Chunk operations but when I use `timed` on the test suite it takes approximately the same time on RC21 as it did on RC20.

**Pull request merged**
