### PR TITLE
Reintroduction of #349, fixes performance for very small Iterables

### PR DESCRIPTION
**Pull request by OlegYch**
For some reason it was gone from 0.3.2

### CODE REVIEW

**Review by adamgfraser — CHANGES_REQUESTED** [review]
Thanks! Looks like this just needs a format and it will be good to go!

**Review by adamgfraser — APPROVED** [review]

**Comment by adamgfraser** [comment]
@OlegYch Did you do any benchmarking to see whether this actually makes a difference? The main idea behind this was to avoid forking a fiber when there is only one element but ZIO already does this optimization internally now.

**Comment by alexdupre** [comment]
We spotted the issue because we had a *huge* increase in resource usage when we upgraded from version 0.3.1 to 0.3.4. I think @OlegYch identified the issue in the removed optimization, he can surely tell more.

**Comment by OlegYch** [comment]
i did do the benchmarking, but i can't remember which version of zio i tested the regression and fix against, i'll try to make a repro again...

**Comment by OlegYch** [comment]
i confirm the issue is present with zio-query 0.3.4 on zio 2.0.6 and 2.0.8

**Pull request merged**
