### PR TITLE
Minor Code Cleanup

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by OlegYch** [comment]
`size` may be an expensive operation (eg on List), i don't think it's a good idea to use it

**Comment by adamgfraser** [comment]
If the collection is large we're about to fork a fiber for every element so seems like a premature optimization.

Benchmark for collecting a list of 100,000 queries in parallel before:

```
[info] Benchmark                                (count)   Mode  Cnt   Score   Error  Units
[info] CollectAllBenchmark.zQueryCollectAllPar   100000  thrpt   20  12.462 ± 0.800  ops/s
```

And after:

```
[info] Benchmark                                (count)   Mode  Cnt   Score   Error  Units
[info] CollectAllBenchmark.zQueryCollectAllPar   100000  thrpt   20  12.311 ± 0.175  ops/s
```

**Comment by OlegYch** [comment]
some other inefficiency might hide it for now, but it's still not a good idea

**Comment by adamgfraser** [comment]
It isn't a matter of some other inefficiency hiding it, it is a matter of the running time of forking and joining fibers being a different order of magnitude than collection operations.

**Pull request merged**
