### PR TITLE
Try To Upgrade ZIO Version

### PR DESCRIPTION
**Pull request by adamgfraser**

### CODE REVIEW

**Comment by adamgfraser** [comment]
@ghostdogpr All tests passing very quickly with `Chunk` swapped out for `Vector` so there is definitely something fishy going on with `Chunk`.

**Comment by ghostdogpr** [comment]
Is it really quick?
`+ zipPar does not prevent batching - repeated: 100, 3 m 57 s (54.83%)`
`+ efficiency of large queries - 2 m 40 s (37.07%)`

Isn't it just because you set a very long timeout?

**Comment by adamgfraser** [comment]
If you look at the CI logs the entire test suite finished in about 7 seconds. If you’re good with everything else I can clean this up and merge it.

**Comment by ghostdogpr** [comment]
I see
```
[info] Ran 21 tests in 4 m 4 s: 21 succeeded, 0 ignored, 0 failed
[info] Done
[success] Total time: 279 s (04:39), completed Jun 20, 2020 3:13:25 PM
```
🤔

**Comment by adamgfraser** [comment]
You're right. Sorry, I must have been looking at the wrong thing. Well that is interesting.

**Pull request closed without merging**
